model:
  hidden_dim: 2048
  num_hidden_layers: 6

train:
  max_batch_size: 2048
  total_epochs: 1000
  warmup_epochs: 3
  lr: 1.0e-4
  pde_weight: 0.1

dataset:
  max_iter: 1000
  num_train_samples: 100_000
  num_val_samples: 1_000
  num_train_workers: 16
  num_val_workers: 16
  batch_size: 8