model:
  hidden_dim: 2048
  num_hidden_layers: 12
  time_token_dim: 2048
  compute_dz_dt: False
  compute_dz_dc: True

train:
  max_batch_size: 2048
  total_epochs: 5_000
  warmup_epochs: 3
  lr: 1.0e-4
  pde_weight: 1.0e-4
  pde_weight_warmup_epochs: 1_000
  use_clipped_nans: True

dataset:
  max_iter: 40
  max_magnitude: 1.0e+2
  num_train_samples: 100_000
  num_val_samples: 1_000
  num_train_workers: 16
  num_val_workers: 16
  batch_size: 64
  biased_sampling: True
  log_scale: False
  real_range: [-2.0, 1.0]
  imag_range: [-1.5, 1.5]